name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: ['master']
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: JrGithubActionTest
          # Container registry password
          password: LhNHQ6fCe7XGzlzquGddYjONZdD8Z07LVg/jGKUq/X+ACRCNTm/5
          # Container registry server url
          login-server: jrgithubactiontest.azurecr.io
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jrgithubactiontest.azurecr.io/hello-world-app:${{ github.sha }}
          file: ./Dockerfile
      
  deployToAKS:
    permissions:
      actions: read
      contents: read
      id-token: write
      
    runs-on: ubuntu-latest
    needs: [buildImage]
    environment: Production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: '87099859-0331-4b6a-9e76-7e82dde52222'
          tenant-id: '225a1d03-5836-4cdb-ad59-82fefc9d7030'
          subscription-id: 'ddafef07-9cf5-475d-a9df-722580efb076'
    
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
        
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 'jr-github-action'
          # AKS Cluster Name
          cluster-name: 'JrGitHubActionTest0503'
          # AKS Cluster Subscription
          subscription: 'ddafef07-9cf5-475d-a9df-722580efb076'
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
          
          
      #Substitute environment variables in a field    
      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.1.0
        env:
          MONGODB_URI: 'mongodb://jr-githubaction-test-0503:22DrM4Ec1Uw3HyC6fjxRz88sLWkKoWHVtpI8NrQikIDSGtUJOwYw1UJKrvPZrNtyj45XkJB1GwiXACDb5aiUhg==@jr-githubaction-test-0503.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@jr-githubaction-test-0503@'
          CONTAINER_NAME: hello-world-app:${{ github.sha }}
          AZURE_CONTAINER_REGISTRY: jrgithubactiontest.azurecr.io
        with:
          #File to run substitutions on
          input:
            kubernetes/hello-world-deployment.yaml
          #File to write result to
          output:
            hello-world-deployment.yaml

      
          
      - name: Deploy application to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with: 
          action: deploy
          manifests: |
            kubernetes/hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            jrgithubactiontest.azurecr.io/hello-world-app:${{ github.sha }}
